# Generated by Django 6.0.6 on 2026-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
