# Generated by Django 6.0.6 on 2026-06-08 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('match_report', 'Match Report'), ('announcement', 'Announcement'), ('player_spotlight', 'Player Spotlight'), ('stats', 'Stats'), ('general', 'General')], default='general', max_length=30)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('emoji', models.CharField(default='📰', max_length=10)),
                ('bg_color', models.CharField(default='#0D2E4B', max_length=7)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
