# Generated by Django 6.0.6 on 2026-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author_title',
            field=models.CharField(blank=True, default='Tournament Committee', max_length=100),
        ),
    ]
