# Generated by Django 6.0.6 on 2026-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_author_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/'),
        ),
    ]
